cargo-features = ["edition2024"]

[package]
name = "icarus"
version = "0.1.0"
edition = "2024"

[lib]


[dependencies]
frunk = { version = "0.4.3", features = ["std"] }
nalgebra = "0.33.2"
sdl3 = { path = "sdl3" }
